from .fetch_youtube_data import handle_youtube_query
from .query_generator import get_sql_from_ollama
def get_data(prompt):
    question = prompt
    sql = get_sql_from_ollama(question)

    if sql:
        print("SQL Generated by LLaMA:\n", sql)
        output = handle_youtube_query(sql)
        print("Query Result:\n", output)
    else:
        print("Failed to generate SQL.")

# ----------------------------
# 🧪 Run Main
# ----------------------------
if __name__ == "__main__":
    prompt = 'give me 5 rows and any 2 columns of data from us'
    get_data(prompt=prompt )